package maxi.rmreporting.api.international;

public interface RetentionManagersForexTableRowsInt {
	
	int TEAMS_LIST_ROW_NUMBER_INT = 0;
	int RM_LIST_ROW_NUMBER_INT = 1;
	int NET_DEPOSITS_ROW_NUMBER_INT = 2; 
	int TOTAL_DEPOSIT_ROWNUM_INT = 3;
	int CREDITS_REDEPOSITS_INT = 4;
	int CREDITS_PRIOR_INT = 5;
	int CREDITS_DIVIDED_BY_DEPOSITS_INT = 6;
	int CREDITS_FOR_LOCK_ROWNUM_INT = 7;
	int DEPOSITS_AFTER_LOCK_ROWNUM_INT = 8;
	int DEPOSITS_DIV_CREDITS_FOR_LOCK_ROWNUM_INT = 9;		
	int REOPENING_POSITIONS_ROWNUM_INT = 10;
	int DEPOSITS_AFTER_REOPEN_INT = 11;
	int DEPOSITS_DIV_CREDITS_AFTER_REOP_ROWNUM_INT = 12;	
	int TOTAL_WITHDRAWALS_ROWNUM_INT = 13;
	int NUMBER_OF_DEPOSITS_ROWNUM_INT = 14;
	int NUMBER_OF_DEPOSITED_USERS_ROWNUM_INT = 15;
	int AVERAGE_DEPOSIT_ROWNUM_INT = 16;
	int VOLUME_ROWNUM_INT = 17;
	int DEALS_PNL_ROWNUM_INT = 18;
	int TRADES_NUMBER_ROWNUM_INT = 19;
	int TRADES_OPENED_VIA_DEALING_ROWNUM_INT = 20;
	int ACTIVE_USERS_ROWNUM_INT = 21;
	int TOTAL_CLIENTS_EOP_ROWNUM_INT = 22;
	int ACTIVE_USERS_DIV_TOTAL_CLIENTS_ROWNUM_INT = 23;
	int ACCOUNT_VALUE_BOP_ROWNUM_INT = 24;
	int ACCOUNT_VALUE_EOP_ROWNUM_INT = 25;
	int NEW_USERS60_ROWNUM_INT = 26;
	int NEW_USERS_MORE5_ROWNUM_INT = 27;
	int ACTIVE_NEW_USERS_ROWNUM_INT = 28;
	int NEW_USERS_VOLUME_ROWNUM_INT = 29;
	int NEW_USERS_VOL_DIVIDED_VOL_ROWNUM_INT = 30;
	int NEW_USERS_REDEPOSITED_MORE450_ROWNUM_INT = 31;
	int NEW_USERS_REDEPOSITS_NUMBER_MORE450_ROWNUM_INT = 32;
	int NEW_USERS_REDEPOSITS_SUM_ROWNUM_INT = 33;
}
