package maxi.rmreporting.api.russian;

public interface LeftColumnTitlesList {

	String[] LEFT_COLUMN_TITLES_LIST = new String[] {

			"	Net Deposit	"	,
			"	Total Deposit	"	,
			"	Credits redeposits	"	,
			"	Credits Prior	"	,
			"	% Credit/Deposit	"	,
			"	Credits for locking positions	"	,
			"	Deposits after locking positions	"	,
			"	% Deposit/Credit for lock	"	,
			"	Reopening positions	"	,
			"	Deposits after reopening positions	"	,
			"	% Deposit/Credit after reopening	"	,
			"	Total Withdraw	"	,
			"	Number of deposits	"	,
			"	Deposits > 100	"	,
			"	Deposits > 450	"	,
			"	Deposits > 1000	"	,
			"	# Deposited Users	"	,
			"	# Deposited Users >100	"	,
			"	# Deposited Users >450	"	,
			"	# Deposited Users >1000	"	,
			"	Average Deposit	"	,
			"	Volume	"	,
			"	Deals Pnl	"	,
			"	# Trades	"	,
			"	# Trades opened via dealing	"	,
			"	# Active Users	"	,
			"	Total clients EoP	"	,
			"	% Active Users / Total clients	"	,
			"	Account value BoP	"	,
			"	Account value EoP	"	,
			"	Avg Bal per client	"	,
			"	Avg deal size	"	,
			"	Avg volume per trader	"	,
			"	Avg P&L from client	"	,
			"	Avg P&l from trade	"	,
			"	vol/p&l ratio	"	,
			"	Avg # Deals per client	"	,
			"	change in account value	"	,
			"	Vol/200/EoM	"	,
			"	Balance >= 100$	"	,
			"	%Bal>=100/Total clients	"	,
			"	Balance >=1000$	"	,
			"	%Bal>=1000/Total clients	"	,
			"	Active Users with Balance>=1000	"	,
			"	Active Balance >=1000	"	,
			"	Active Users with Balance>=100	"	,
			"	Active Users with Balance>=100/Total Users	"	,
			"	DT=>5	"	,
			"	DT=>5/Total Clients	"	,
			"	New users (<60 days)	"	,
			"	New users DT=>5	"	,
			"	Active new users	"	,
			"	New users Volume	"	,
			"	New users volume /All volume	"	,
			"	New users redeposited (>450USD)	"	,
			"	New user's redeposits (>450 USD)	"	,
			"	New users redeposits sum	"	


	};
}
